/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedWorkRecordsIndexRouteImport } from './routes/_authenticated/work-records/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedWorkRecordsTemplatesRouteImport } from './routes/_authenticated/work-records/templates'
import { Route as AuthenticatedWorkRecordsOperationsRouteImport } from './routes/_authenticated/work-records/operations'
import { Route as AuthenticatedWorkRecordsNewRouteImport } from './routes/_authenticated/work-records/new'
import { Route as AuthenticatedWorkRecordsRecordIdRouteImport } from './routes/_authenticated/work-records/$recordId'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedPlatformRolesRouteImport } from './routes/_authenticated/platform/roles'
import { Route as AuthenticatedPlatformDictionariesRouteImport } from './routes/_authenticated/platform/dictionaries'
import { Route as AuthenticatedPlatformCalendarsRouteImport } from './routes/_authenticated/platform/calendars'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedWorkRecordsTemplatesIndexRouteImport } from './routes/_authenticated/work-records/templates.index'
import { Route as AuthenticatedPlatformUsersIndexRouteImport } from './routes/_authenticated/platform/users/index'
import { Route as AuthenticatedWorkRecordsRecordIdEditRouteImport } from './routes/_authenticated/work-records/$recordId.edit'
import { Route as AuthenticatedWorkRecordsTemplatesTemplateIdDesignerRouteImport } from './routes/_authenticated/work-records/templates.$templateId.designer'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkRecordsIndexRoute =
  AuthenticatedWorkRecordsIndexRouteImport.update({
    id: '/work-records/',
    path: '/work-records/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedWorkRecordsTemplatesRoute =
  AuthenticatedWorkRecordsTemplatesRouteImport.update({
    id: '/work-records/templates',
    path: '/work-records/templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkRecordsOperationsRoute =
  AuthenticatedWorkRecordsOperationsRouteImport.update({
    id: '/work-records/operations',
    path: '/work-records/operations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkRecordsNewRoute =
  AuthenticatedWorkRecordsNewRouteImport.update({
    id: '/work-records/new',
    path: '/work-records/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkRecordsRecordIdRoute =
  AuthenticatedWorkRecordsRecordIdRouteImport.update({
    id: '/work-records/$recordId',
    path: '/work-records/$recordId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedPlatformRolesRoute =
  AuthenticatedPlatformRolesRouteImport.update({
    id: '/platform/roles',
    path: '/platform/roles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformDictionariesRoute =
  AuthenticatedPlatformDictionariesRouteImport.update({
    id: '/platform/dictionaries',
    path: '/platform/dictionaries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformCalendarsRoute =
  AuthenticatedPlatformCalendarsRouteImport.update({
    id: '/platform/calendars',
    path: '/platform/calendars',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkRecordsTemplatesIndexRoute =
  AuthenticatedWorkRecordsTemplatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkRecordsTemplatesRoute,
  } as any)
const AuthenticatedPlatformUsersIndexRoute =
  AuthenticatedPlatformUsersIndexRouteImport.update({
    id: '/platform/users/',
    path: '/platform/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkRecordsRecordIdEditRoute =
  AuthenticatedWorkRecordsRecordIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedWorkRecordsRecordIdRoute,
  } as any)
const AuthenticatedWorkRecordsTemplatesTemplateIdDesignerRoute =
  AuthenticatedWorkRecordsTemplatesTemplateIdDesignerRouteImport.update({
    id: '/$templateId/designer',
    path: '/$templateId/designer',
    getParentRoute: () => AuthenticatedWorkRecordsTemplatesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/platform/calendars': typeof AuthenticatedPlatformCalendarsRoute
  '/platform/dictionaries': typeof AuthenticatedPlatformDictionariesRoute
  '/platform/roles': typeof AuthenticatedPlatformRolesRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/work-records/$recordId': typeof AuthenticatedWorkRecordsRecordIdRouteWithChildren
  '/work-records/new': typeof AuthenticatedWorkRecordsNewRoute
  '/work-records/operations': typeof AuthenticatedWorkRecordsOperationsRoute
  '/work-records/templates': typeof AuthenticatedWorkRecordsTemplatesRouteWithChildren
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/work-records/': typeof AuthenticatedWorkRecordsIndexRoute
  '/work-records/$recordId/edit': typeof AuthenticatedWorkRecordsRecordIdEditRoute
  '/platform/users/': typeof AuthenticatedPlatformUsersIndexRoute
  '/work-records/templates/': typeof AuthenticatedWorkRecordsTemplatesIndexRoute
  '/work-records/templates/$templateId/designer': typeof AuthenticatedWorkRecordsTemplatesTemplateIdDesignerRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/platform/calendars': typeof AuthenticatedPlatformCalendarsRoute
  '/platform/dictionaries': typeof AuthenticatedPlatformDictionariesRoute
  '/platform/roles': typeof AuthenticatedPlatformRolesRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/work-records/$recordId': typeof AuthenticatedWorkRecordsRecordIdRouteWithChildren
  '/work-records/new': typeof AuthenticatedWorkRecordsNewRoute
  '/work-records/operations': typeof AuthenticatedWorkRecordsOperationsRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/work-records': typeof AuthenticatedWorkRecordsIndexRoute
  '/work-records/$recordId/edit': typeof AuthenticatedWorkRecordsRecordIdEditRoute
  '/platform/users': typeof AuthenticatedPlatformUsersIndexRoute
  '/work-records/templates': typeof AuthenticatedWorkRecordsTemplatesIndexRoute
  '/work-records/templates/$templateId/designer': typeof AuthenticatedWorkRecordsTemplatesTemplateIdDesignerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/platform/calendars': typeof AuthenticatedPlatformCalendarsRoute
  '/_authenticated/platform/dictionaries': typeof AuthenticatedPlatformDictionariesRoute
  '/_authenticated/platform/roles': typeof AuthenticatedPlatformRolesRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/work-records/$recordId': typeof AuthenticatedWorkRecordsRecordIdRouteWithChildren
  '/_authenticated/work-records/new': typeof AuthenticatedWorkRecordsNewRoute
  '/_authenticated/work-records/operations': typeof AuthenticatedWorkRecordsOperationsRoute
  '/_authenticated/work-records/templates': typeof AuthenticatedWorkRecordsTemplatesRouteWithChildren
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/work-records/': typeof AuthenticatedWorkRecordsIndexRoute
  '/_authenticated/work-records/$recordId/edit': typeof AuthenticatedWorkRecordsRecordIdEditRoute
  '/_authenticated/platform/users/': typeof AuthenticatedPlatformUsersIndexRoute
  '/_authenticated/work-records/templates/': typeof AuthenticatedWorkRecordsTemplatesIndexRoute
  '/_authenticated/work-records/templates/$templateId/designer': typeof AuthenticatedWorkRecordsTemplatesTemplateIdDesignerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/errors/$error'
    | '/platform/calendars'
    | '/platform/dictionaries'
    | '/platform/roles'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/work-records/$recordId'
    | '/work-records/new'
    | '/work-records/operations'
    | '/work-records/templates'
    | '/settings/'
    | '/work-records/'
    | '/work-records/$recordId/edit'
    | '/platform/users/'
    | '/work-records/templates/'
    | '/work-records/templates/$templateId/designer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/platform/calendars'
    | '/platform/dictionaries'
    | '/platform/roles'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/work-records/$recordId'
    | '/work-records/new'
    | '/work-records/operations'
    | '/settings'
    | '/work-records'
    | '/work-records/$recordId/edit'
    | '/platform/users'
    | '/work-records/templates'
    | '/work-records/templates/$templateId/designer'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/platform/calendars'
    | '/_authenticated/platform/dictionaries'
    | '/_authenticated/platform/roles'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/work-records/$recordId'
    | '/_authenticated/work-records/new'
    | '/_authenticated/work-records/operations'
    | '/_authenticated/work-records/templates'
    | '/_authenticated/settings/'
    | '/_authenticated/work-records/'
    | '/_authenticated/work-records/$recordId/edit'
    | '/_authenticated/platform/users/'
    | '/_authenticated/work-records/templates/'
    | '/_authenticated/work-records/templates/$templateId/designer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work-records/': {
      id: '/_authenticated/work-records/'
      path: '/work-records'
      fullPath: '/work-records/'
      preLoaderRoute: typeof AuthenticatedWorkRecordsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/work-records/templates': {
      id: '/_authenticated/work-records/templates'
      path: '/work-records/templates'
      fullPath: '/work-records/templates'
      preLoaderRoute: typeof AuthenticatedWorkRecordsTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work-records/operations': {
      id: '/_authenticated/work-records/operations'
      path: '/work-records/operations'
      fullPath: '/work-records/operations'
      preLoaderRoute: typeof AuthenticatedWorkRecordsOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work-records/new': {
      id: '/_authenticated/work-records/new'
      path: '/work-records/new'
      fullPath: '/work-records/new'
      preLoaderRoute: typeof AuthenticatedWorkRecordsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work-records/$recordId': {
      id: '/_authenticated/work-records/$recordId'
      path: '/work-records/$recordId'
      fullPath: '/work-records/$recordId'
      preLoaderRoute: typeof AuthenticatedWorkRecordsRecordIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/platform/roles': {
      id: '/_authenticated/platform/roles'
      path: '/platform/roles'
      fullPath: '/platform/roles'
      preLoaderRoute: typeof AuthenticatedPlatformRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform/dictionaries': {
      id: '/_authenticated/platform/dictionaries'
      path: '/platform/dictionaries'
      fullPath: '/platform/dictionaries'
      preLoaderRoute: typeof AuthenticatedPlatformDictionariesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform/calendars': {
      id: '/_authenticated/platform/calendars'
      path: '/platform/calendars'
      fullPath: '/platform/calendars'
      preLoaderRoute: typeof AuthenticatedPlatformCalendarsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work-records/templates/': {
      id: '/_authenticated/work-records/templates/'
      path: '/'
      fullPath: '/work-records/templates/'
      preLoaderRoute: typeof AuthenticatedWorkRecordsTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedWorkRecordsTemplatesRoute
    }
    '/_authenticated/platform/users/': {
      id: '/_authenticated/platform/users/'
      path: '/platform/users'
      fullPath: '/platform/users/'
      preLoaderRoute: typeof AuthenticatedPlatformUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work-records/$recordId/edit': {
      id: '/_authenticated/work-records/$recordId/edit'
      path: '/edit'
      fullPath: '/work-records/$recordId/edit'
      preLoaderRoute: typeof AuthenticatedWorkRecordsRecordIdEditRouteImport
      parentRoute: typeof AuthenticatedWorkRecordsRecordIdRoute
    }
    '/_authenticated/work-records/templates/$templateId/designer': {
      id: '/_authenticated/work-records/templates/$templateId/designer'
      path: '/$templateId/designer'
      fullPath: '/work-records/templates/$templateId/designer'
      preLoaderRoute: typeof AuthenticatedWorkRecordsTemplatesTemplateIdDesignerRouteImport
      parentRoute: typeof AuthenticatedWorkRecordsTemplatesRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedWorkRecordsRecordIdRouteChildren {
  AuthenticatedWorkRecordsRecordIdEditRoute: typeof AuthenticatedWorkRecordsRecordIdEditRoute
}

const AuthenticatedWorkRecordsRecordIdRouteChildren: AuthenticatedWorkRecordsRecordIdRouteChildren =
  {
    AuthenticatedWorkRecordsRecordIdEditRoute:
      AuthenticatedWorkRecordsRecordIdEditRoute,
  }

const AuthenticatedWorkRecordsRecordIdRouteWithChildren =
  AuthenticatedWorkRecordsRecordIdRoute._addFileChildren(
    AuthenticatedWorkRecordsRecordIdRouteChildren,
  )

interface AuthenticatedWorkRecordsTemplatesRouteChildren {
  AuthenticatedWorkRecordsTemplatesIndexRoute: typeof AuthenticatedWorkRecordsTemplatesIndexRoute
  AuthenticatedWorkRecordsTemplatesTemplateIdDesignerRoute: typeof AuthenticatedWorkRecordsTemplatesTemplateIdDesignerRoute
}

const AuthenticatedWorkRecordsTemplatesRouteChildren: AuthenticatedWorkRecordsTemplatesRouteChildren =
  {
    AuthenticatedWorkRecordsTemplatesIndexRoute:
      AuthenticatedWorkRecordsTemplatesIndexRoute,
    AuthenticatedWorkRecordsTemplatesTemplateIdDesignerRoute:
      AuthenticatedWorkRecordsTemplatesTemplateIdDesignerRoute,
  }

const AuthenticatedWorkRecordsTemplatesRouteWithChildren =
  AuthenticatedWorkRecordsTemplatesRoute._addFileChildren(
    AuthenticatedWorkRecordsTemplatesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedPlatformCalendarsRoute: typeof AuthenticatedPlatformCalendarsRoute
  AuthenticatedPlatformDictionariesRoute: typeof AuthenticatedPlatformDictionariesRoute
  AuthenticatedPlatformRolesRoute: typeof AuthenticatedPlatformRolesRoute
  AuthenticatedWorkRecordsRecordIdRoute: typeof AuthenticatedWorkRecordsRecordIdRouteWithChildren
  AuthenticatedWorkRecordsNewRoute: typeof AuthenticatedWorkRecordsNewRoute
  AuthenticatedWorkRecordsOperationsRoute: typeof AuthenticatedWorkRecordsOperationsRoute
  AuthenticatedWorkRecordsTemplatesRoute: typeof AuthenticatedWorkRecordsTemplatesRouteWithChildren
  AuthenticatedWorkRecordsIndexRoute: typeof AuthenticatedWorkRecordsIndexRoute
  AuthenticatedPlatformUsersIndexRoute: typeof AuthenticatedPlatformUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedPlatformCalendarsRoute: AuthenticatedPlatformCalendarsRoute,
  AuthenticatedPlatformDictionariesRoute:
    AuthenticatedPlatformDictionariesRoute,
  AuthenticatedPlatformRolesRoute: AuthenticatedPlatformRolesRoute,
  AuthenticatedWorkRecordsRecordIdRoute:
    AuthenticatedWorkRecordsRecordIdRouteWithChildren,
  AuthenticatedWorkRecordsNewRoute: AuthenticatedWorkRecordsNewRoute,
  AuthenticatedWorkRecordsOperationsRoute:
    AuthenticatedWorkRecordsOperationsRoute,
  AuthenticatedWorkRecordsTemplatesRoute:
    AuthenticatedWorkRecordsTemplatesRouteWithChildren,
  AuthenticatedWorkRecordsIndexRoute: AuthenticatedWorkRecordsIndexRoute,
  AuthenticatedPlatformUsersIndexRoute: AuthenticatedPlatformUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
