{{- if .Values.serviceAccount.create }}
{{- $root := . -}}
{{- range $appName, $app := .Values.apps }}
{{- if $app.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aegisops.componentServiceAccountName" (list $root $appName) }}
  labels:
    {{- include "aegisops.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $appName }}
  annotations:
    {{- toYaml $root.Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
