{{- if .Values.apps.server.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aegisops.fullname" . }}-server-secret
  labels:
    {{- include "aegisops.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
type: Opaque
stringData:
  AIOPS_INTEGRATIONS_ZABBIX_WEBHOOK_TOKEN: {{ required "security.zabbixWebhookSigningSecret is required" .Values.security.zabbixWebhookSigningSecret | quote }}
{{- end }}
