{{- $root := . -}}
{{- range $appName, $app := .Values.apps }}
{{- if $app.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aegisops.fullname" $root }}-{{ $appName }}
  labels:
    {{- include "aegisops.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $appName }}
spec:
  type: ClusterIP
  selector:
    {{- include "aegisops.selectorLabels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $appName }}
  ports:
    - name: http
      port: {{ $app.port }}
      targetPort: http
{{- end }}
{{- end }}
