from pydantic import AliasChoices, Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_prefix="AIOPS_AGENT_",
        env_file=".env",
        extra="ignore",
        populate_by_name=True,
    )

    internal_token: str = "dev-internal-token"

    provider: str = "aiops-agent"
    model: str = "langgraph-deterministic"

    # Accept both:
    # - AIOPS_AGENT_AGENT_NAME: canonical name generated by env_prefix + field name
    # - AIOPS_AGENT_NAME: shorter compose-friendly alias already used by infra/docker-compose.yml
    agent_name: str = Field(
        default="aegisops_diagnosis_graph",
        validation_alias=AliasChoices("AIOPS_AGENT_AGENT_NAME", "AIOPS_AGENT_NAME"),
    )

    default_locale: str = "zh-CN"
    contract_version: str = "agent-diagnosis.v1"

    # deterministic | openai-compatible
    generation_mode: str = "deterministic"

    def normalized_generation_mode(self) -> str:
        value = (self.generation_mode or "deterministic").strip().lower()
        if value not in {"deterministic", "openai-compatible"}:
            return "deterministic"
        return value


settings = Settings()
