from pydantic import AliasChoices, Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_prefix="AIOPS_AGENT_",
        env_file=".env",
        extra="ignore",
        populate_by_name=True,
    )

    # Phase 8.0 SaaS multi-tenant hardening.
    inbound_oauth2_issuer: str = "http://localhost:8089/realms/aegisops"
    inbound_oauth2_jwks_url: str = (
        "http://localhost:8089/realms/aegisops/protocol/openid-connect/certs"
    )
    inbound_oauth2_audience: str = "aiops-agent-api"
    outbound_oauth2_token_url: str = (
        "http://localhost:8089/realms/aegisops/protocol/openid-connect/token"
    )
    outbound_oauth2_client_id: str = "aiops-agent"
    outbound_oauth2_client_secret: str = "dev-aiops-agent-client-secret"
    outbound_oauth2_scope: str = (
        "evidence:read cases:read checkpoint:read checkpoint:write "
        "memory:read memory:write plugin:authorize"
    )

    provider: str = "aiops-agent"
    model: str = "langgraph-deterministic"

    # Accept both:
    # - AIOPS_AGENT_AGENT_NAME: canonical name generated by env_prefix + field name
    # - AIOPS_AGENT_NAME: shorter compose-friendly alias already used by infra/docker-compose.yml
    agent_name: str = Field(
        default="aegisops_diagnosis_graph",
        validation_alias=AliasChoices("AIOPS_AGENT_AGENT_NAME", "AIOPS_AGENT_NAME"),
    )

    default_locale: str = "zh-CN"
    contract_version: str = "agent-diagnosis.v1"

    # deterministic | mock | deterministic-evidence | openai-compatible | workflow
    generation_mode: str = "deterministic"

    # OpenAI-compatible /chat/completions settings.
    # Examples:
    #   AIOPS_AGENT_OPENAI_BASE_URL=https://api.openai.com/v1
    #   AIOPS_AGENT_OPENAI_BASE_URL=https://api.deepseek.com/v1
    #   AIOPS_AGENT_OPENAI_BASE_URL=http://localhost:11434/v1
    openai_base_url: str = ""
    openai_api_key: str = ""
    openai_timeout_seconds: float = 30.0
    openai_temperature: float = 0.2
    openai_max_tokens: int = 1200

    # Some OpenAI-compatible gateways do not support response_format.
    # Keep enabled by default for stricter JSON when provider supports it.
    openai_response_format_enabled: bool = True

    # Work-record generation is capability-specific so Incident diagnosis keeps
    # its existing provider and graph configuration.
    work_record_provider: str = "deterministic"
    dify_base_url: str = ""
    dify_work_record_api_key: str = ""
    dify_work_record_workflow_id: str = ""
    dify_work_record_workflow_version: str = "work-record-2026-07-19.1"
    dify_timeout_seconds: float = Field(default=75.0, gt=0)
    dify_max_retries: int = Field(default=2, ge=0, le=5)
    dify_max_input_bytes: int = Field(default=65536, gt=0)
    dify_user_hmac_secret: str = ""

    # Phase4.3 evidence tool. When disabled, the agent uses
    # DisabledEvidenceClient and the raw response shows unavailable markers.
    evidence_enabled: bool = False
    evidence_base_url: str = ""
    evidence_timeout_seconds: float = 5.0

    # Phase4.4 observability. When disabled, response.raw will not contain
    # agentRun / agentEval sections.
    trace_enabled: bool = True
    eval_enabled: bool = True

    # Phase 7 modular workflow. The Java-facing v1 contract stays stable while
    # these flags control optional internal graph capabilities.
    workflow_api_base_url: str = "http://localhost:8080"
    workflow_graph_version: str = "phase8.0-saas-tenant-hardening"
    workflow_request_timeout_seconds: float = 5.0
    workflow_max_evidence_items: int = 8
    workflow_max_similar_cases: int = 5
    workflow_max_memories: int = 5
    workflow_checkpoint_ttl_seconds: int = 86400
    workflow_max_agent_messages: int = 20
    workflow_evidence_enabled: bool = False
    workflow_case_retrieval_enabled: bool = False
    workflow_human_checkpoint_enabled: bool = False
    workflow_multi_agent_enabled: bool = False
    workflow_memory_enabled: bool = False
    workflow_memory_write_enabled: bool = False

    # Phase 8.1 plugin tool policy. When enabled, the agent calls
    # /internal/agent/plugins/tools/authorize before using allowlisted tools.
    # Default false to avoid blocking local development without plugins enabled.
    # SaaS deployments should set AIOPS_AGENT_WORKFLOW_PLUGIN_TOOL_POLICY_ENABLED=true.
    workflow_plugin_tool_policy_enabled: bool = False

    # Phase 9.0 observability.
    log_level: str = "INFO"
    observability_enabled: bool = True

    def normalized_generation_mode(self) -> str:
        value = (self.generation_mode or "deterministic").strip().lower()
        if value not in {
            "deterministic",
            "mock",
            "deterministic-evidence",
            "openai-compatible",
            "workflow",
        }:
            return "deterministic"
        return value

    def normalized_openai_base_url(self) -> str:
        value = (self.openai_base_url or "").strip()
        while value.endswith("/"):
            value = value[:-1]
        return value

    def normalized_work_record_provider(self) -> str:
        value = (self.work_record_provider or "deterministic").strip().lower()
        if value not in {"deterministic", "dify"}:
            return "deterministic"
        return value

    def normalized_dify_base_url(self) -> str:
        return (self.dify_base_url or "").strip().rstrip("/")

    def normalized_evidence_base_url(self) -> str:
        value = (self.evidence_base_url or "").strip()
        while value.endswith("/"):
            value = value[:-1]
        return value


settings = Settings()
