from pydantic import AliasChoices, Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_prefix="AIOPS_AGENT_",
        env_file=".env",
        extra="ignore",
        populate_by_name=True,
    )

    internal_token: str = "dev-internal-token"

    provider: str = "aiops-agent"
    model: str = "langgraph-deterministic"

    # Accept both:
    # - AIOPS_AGENT_AGENT_NAME: canonical name generated by env_prefix + field name
    # - AIOPS_AGENT_NAME: shorter compose-friendly alias already used by infra/docker-compose.yml
    agent_name: str = Field(
        default="aegisops_diagnosis_graph",
        validation_alias=AliasChoices("AIOPS_AGENT_AGENT_NAME", "AIOPS_AGENT_NAME"),
    )

    default_locale: str = "zh-CN"
    contract_version: str = "agent-diagnosis.v1"

    # deterministic | openai-compatible
    generation_mode: str = "deterministic"

    # OpenAI-compatible /chat/completions settings.
    # Examples:
    #   AIOPS_AGENT_OPENAI_BASE_URL=https://api.openai.com/v1
    #   AIOPS_AGENT_OPENAI_BASE_URL=https://api.deepseek.com/v1
    #   AIOPS_AGENT_OPENAI_BASE_URL=http://localhost:11434/v1
    openai_base_url: str = ""
    openai_api_key: str = ""
    openai_timeout_seconds: float = 30.0
    openai_temperature: float = 0.2
    openai_max_tokens: int = 1200

    # Some OpenAI-compatible gateways do not support response_format.
    # Keep enabled by default for stricter JSON when provider supports it.
    openai_response_format_enabled: bool = True

    # Phase4.3 evidence tool. When disabled, the agent uses
    # DisabledEvidenceClient and the raw response shows unavailable markers.
    evidence_enabled: bool = False
    evidence_base_url: str = ""
    evidence_internal_token: str = "dev-internal-token"
    evidence_timeout_seconds: float = 5.0

    # Phase4.4 observability. When disabled, response.raw will not contain
    # agentRun / agentEval sections.
    trace_enabled: bool = True
    eval_enabled: bool = True

    # Phase 7 modular workflow. The Java-facing v1 contract stays stable while
    # these flags control optional internal graph capabilities.
    workflow_api_base_url: str = "http://localhost:8080"
    workflow_graph_version: str = "phase7.3-agent-memory"
    workflow_request_timeout_seconds: float = 5.0
    workflow_max_evidence_items: int = 8
    workflow_max_similar_cases: int = 5
    workflow_max_memories: int = 5
    workflow_checkpoint_ttl_seconds: int = 86400
    workflow_max_agent_messages: int = 20
    workflow_evidence_enabled: bool = False
    workflow_case_retrieval_enabled: bool = False
    workflow_human_checkpoint_enabled: bool = False
    workflow_multi_agent_enabled: bool = False
    workflow_memory_enabled: bool = False
    workflow_memory_write_enabled: bool = False

    def normalized_generation_mode(self) -> str:
        value = (self.generation_mode or "deterministic").strip().lower()
        if value not in {"deterministic", "openai-compatible"}:
            return "deterministic"
        return value

    def normalized_openai_base_url(self) -> str:
        value = (self.openai_base_url or "").strip()
        while value.endswith("/"):
            value = value[:-1]
        return value

    def normalized_evidence_base_url(self) -> str:
        value = (self.evidence_base_url or "").strip()
        while value.endswith("/"):
            value = value[:-1]
        return value


settings = Settings()
