package io.aegisops.execution.dto;

public record AnsiblePlaybookCreateCommand(
    String id,
    String tenantId,
    String name,
    String description,
    String playbookRef,
    String playbookContent,
    String variablesSchemaJson,
    String allowedTagsJson,
    boolean enabled,
    String createdBy,
    boolean allowLive,
    boolean allowCheckExecution,
    boolean liveRequiresApproval,
    boolean defaultCheckMode,
    String allowedInventoryIdsJson,
    String allowedExtraVarsJson,
    String allowedLiveRiskLevelsJson,
    String allowedCredentialRefIdsJson,
    boolean stdoutStderrMaskingEnabled,
    int maxExtraVarsBytes,
    int timeoutSeconds,
    int liveTimeoutSeconds) {}
