package io.aegisops.workrecord.domain.model;

import java.time.OffsetDateTime;

public record WorkRecordField(
    String id,
    String tenantId,
    String templateId,
    String templateVersionId,
    String fieldName,
    String fieldCode,
    FieldType fieldType,
    boolean required,
    String defaultValue,
    OptionSource optionSource,
    String dictCode,
    String optionsJson,
    String schemaPath,
    int columnSpan,
    String validationJson,
    boolean listVisible,
    boolean filterable,
    boolean exportable,
    boolean statistical,
    int sortOrder,
    boolean enabled,
    OffsetDateTime createdAt,
    OffsetDateTime updatedAt) {
  public WorkRecordField(
      String id,
      String tenantId,
      String templateId,
      String templateVersionId,
      String fieldName,
      String fieldCode,
      FieldType fieldType,
      boolean required,
      String defaultValue,
      OptionSource optionSource,
      String dictCode,
      String optionsJson,
      String schemaPath,
      boolean listVisible,
      boolean filterable,
      boolean exportable,
      boolean statistical,
      int sortOrder,
      boolean enabled,
      OffsetDateTime createdAt,
      OffsetDateTime updatedAt) {
    this(
        id,
        tenantId,
        templateId,
        templateVersionId,
        fieldName,
        fieldCode,
        fieldType,
        required,
        defaultValue,
        optionSource,
        dictCode,
        optionsJson,
        schemaPath,
        2,
        "{}",
        listVisible,
        filterable,
        exportable,
        statistical,
        sortOrder,
        enabled,
        createdAt,
        updatedAt);
  }
}
